### ISSUE TITLE
메인 게임모드 질문

### ISSUE THREAD

**Issue by tladudtn** [HyeN123/osu.gg#2]
해당 유저의 메인 게임모드는 마니아모드인데
![image](https://user-images.githubusercontent.com/39945608/83277101-8ac9a700-a20c-11ea-8690-d446b089a891.png)

osu.gg에서는 기록을 보기위해서 모드를 바꾸면 
모드 옆에 별이 따라다니는데 
버그인가요?
![image](https://user-images.githubusercontent.com/39945608/83277195-ac2a9300-a20c-11ea-88fe-6c23e293bb69.png)

![image](https://user-images.githubusercontent.com/39945608/83277330-db410480-a20c-11ea-8570-2d2aacf96864.png)

**Comment by HyeN123** [comment]
버그는 아니고 선택된 모드에 별 표시를 남겨놓는 기능입니다.

**Comment by HyeN123** [comment]
보더 바텀으로 변경
