### ISSUE TITLE
최근 검색한 닉네임 저장기능

### ISSUE THREAD

**Issue by mirusu400** [HyeN123/osu.gg#3]
대충 쿠키같은거 이용해서 최근 검색한 닉네임 저장하고
오스쩜지지 검색화면에 최근 검색한 닉네임 하이퍼링크로 표시해서 바로 확인가능하게 만드는거 어떤가요

**Comment by HyeN123** [comment]
확인했습니다~ 담주중으로 업뎃할 수 있도록 해볼게여
