### ISSUE TITLE
최근 검색 유저 문제

### ISSUE THREAD

**Issue by tladudtn** [HyeN123/osu.gg#4]
### 1. 존재하지 않는 사용자를 입력하면 최근사용자가 없어지는 문제

아무 유저 검색
![image](https://user-images.githubusercontent.com/39945608/83428305-1b062700-a46d-11ea-8785-fe35fb692bde.png)

존재하지 않는 유저 aa 검색  -
-> 최근 검색한 유저 목록이 사라짐(존재하는 사용자를 검색시 다시 검색 기록이 나타남)
![image](https://user-images.githubusercontent.com/39945608/83428562-9536ab80-a46d-11ea-80dc-9356fc4d2656.png)

존재하지 않는 유저 검색시 뜨는 오류
![image](https://user-images.githubusercontent.com/39945608/83428378-3b35e600-a46d-11ea-8010-44d0af8f4888.png)

### 2. 우연히 알게된 것
위 주소로가면 Undefined 유저가 나옵니다.(실제로 있는 유저)
https://osu-status.herokuapp.com/user/info

**Comment by HyeN123** [comment]
오늘중으로 에러 고쳐서 다시 배포 예정.
